package model;
// Generated Jan 13, 2020 1:30:55 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Employees generated by hbm2java
 */
@Entity
@Table(name="employees"
    ,catalog="s_emp"
)
public class Employees  implements java.io.Serializable {


     private Integer id;
     private String name;
     private String address;
     private int age;
     private String conNumber;

    public Employees() {
    }

    public Employees(String name, String address, int age, String conNumber) {
       this.name = name;
       this.address = address;
       this.age = age;
       this.conNumber = conNumber;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="Id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    
    @Column(name="Name", nullable=false, length=40)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    
    @Column(name="Address", nullable=false, length=50)
    public String getAddress() {
        return this.address;
    }
    
    public void setAddress(String address) {
        this.address = address;
    }

    
    @Column(name="Age", nullable=false)
    public int getAge() {
        return this.age;
    }
    
    public void setAge(int age) {
        this.age = age;
    }

    
    @Column(name="ConNumber", nullable=false, length=11)
    public String getConNumber() {
        return this.conNumber;
    }
    
    public void setConNumber(String conNumber) {
        this.conNumber = conNumber;
    }




}


